/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guisource;

/**
 *
 * @author Antoi
 */
public class FlashcardHome extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FlashcardHome.class.getName());

    /**
     * Creates new form FlashcardHome
     */
    public FlashcardHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        view_flashcards_btn = new javax.swing.JButton();
        edit_flashcards_btn = new javax.swing.JButton();
        main_menu_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FlashCards");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);

        view_flashcards_btn.setBackground(new java.awt.Color(0, 0, 0));
        view_flashcards_btn.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        view_flashcards_btn.setForeground(new java.awt.Color(255, 255, 255));
        view_flashcards_btn.setText("View Flashcards");
        view_flashcards_btn.setAlignmentX(0.5F);
        view_flashcards_btn.setPreferredSize(new java.awt.Dimension(120, 25));
        view_flashcards_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_flashcards_btnActionPerformed(evt);
            }
        });

        edit_flashcards_btn.setBackground(new java.awt.Color(0, 0, 0));
        edit_flashcards_btn.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        edit_flashcards_btn.setForeground(new java.awt.Color(255, 255, 255));
        edit_flashcards_btn.setText("Edit Flashcards");
        edit_flashcards_btn.setPreferredSize(new java.awt.Dimension(120, 25));
        edit_flashcards_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_flashcards_btnActionPerformed(evt);
            }
        });

        main_menu_btn.setBackground(new java.awt.Color(0, 0, 0));
        main_menu_btn.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        main_menu_btn.setForeground(new java.awt.Color(255, 255, 255));
        main_menu_btn.setText("Main Menu");
        main_menu_btn.setMaximumSize(new java.awt.Dimension(120, 25));
        main_menu_btn.setMinimumSize(new java.awt.Dimension(120, 25));
        main_menu_btn.setPreferredSize(new java.awt.Dimension(125, 25));
        main_menu_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_menu_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edit_flashcards_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(view_flashcards_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(main_menu_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(view_flashcards_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edit_flashcards_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main_menu_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edit_flashcards_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_flashcards_btnActionPerformed
        // TODO add your handling code here:
        FlashcardEdit frame_edit = new FlashcardEdit();
        frame_edit.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_edit_flashcards_btnActionPerformed

    private void view_flashcards_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_flashcards_btnActionPerformed
        // TODO add your handling code here:
         FlashcardView frame_view = new FlashcardView();
        frame_view.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_view_flashcards_btnActionPerformed

    private void main_menu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_menu_btnActionPerformed
        // TODO add your handling code here:
        HomePage home_page = new HomePage();
        home_page.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_main_menu_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FlashcardHome().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton edit_flashcards_btn;
    private javax.swing.JButton main_menu_btn;
    private javax.swing.JButton view_flashcards_btn;
    // End of variables declaration//GEN-END:variables
}
