/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guisource;

/**
 *
 * @author Antoi
 */
public class FlashcardCreate extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FlashcardCreate.class.getName());

    /**
     * Creates new form FlashcardCreate
     */
    public FlashcardCreate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        question_input = new javax.swing.JTextField();
        answer_input = new javax.swing.JTextField();
        add_flashcard_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        question_input.setBackground(new java.awt.Color(0, 0, 0));
        question_input.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        question_input.setForeground(new java.awt.Color(255, 255, 255));
        question_input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        question_input.setText("Question");
        question_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question_inputActionPerformed(evt);
            }
        });

        answer_input.setBackground(new java.awt.Color(0, 0, 0));
        answer_input.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        answer_input.setForeground(new java.awt.Color(255, 255, 255));
        answer_input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        answer_input.setText("Answer");
        answer_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer_inputActionPerformed(evt);
            }
        });

        add_flashcard_btn.setBackground(new java.awt.Color(0, 0, 0));
        add_flashcard_btn.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        add_flashcard_btn.setForeground(new java.awt.Color(255, 255, 255));
        add_flashcard_btn.setText("Add Flashcard");
        add_flashcard_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_flashcard_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(question_input, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
            .addComponent(answer_input)
            .addComponent(add_flashcard_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(question_input, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answer_input, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(add_flashcard_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void question_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_question_inputActionPerformed

    private void add_flashcard_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_flashcard_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_flashcard_btnActionPerformed

    private void answer_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer_inputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FlashcardCreate().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_flashcard_btn;
    private javax.swing.JTextField answer_input;
    private javax.swing.JTextField question_input;
    // End of variables declaration//GEN-END:variables
}
