/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guisource;

/**
 *
 * @author Antoi
 */
public class FlashcardDelete extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FlashcardDelete.class.getName());

    /**
     * Creates new form FlashcardDelete
     */
    public FlashcardDelete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        set1_btn = new javax.swing.JRadioButton();
        set3_btn = new javax.swing.JRadioButton();
        set2_btn = new javax.swing.JRadioButton();
        set4_btn = new javax.swing.JRadioButton();
        set5_btn = new javax.swing.JRadioButton();
        set6_btn = new javax.swing.JRadioButton();
        delete_btn = new javax.swing.JButton();
        main_menu_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        set1_btn.setBackground(new java.awt.Color(0, 0, 0));
        set1_btn.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        set1_btn.setForeground(new java.awt.Color(255, 255, 255));
        set1_btn.setText("Flashcard Set 1");

        set3_btn.setBackground(new java.awt.Color(0, 0, 0));
        set3_btn.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        set3_btn.setForeground(new java.awt.Color(255, 255, 255));
        set3_btn.setText("Flashcard Set 3");

        set2_btn.setBackground(new java.awt.Color(0, 0, 0));
        set2_btn.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        set2_btn.setForeground(new java.awt.Color(255, 255, 255));
        set2_btn.setText("Flashcard Set 2");

        set4_btn.setBackground(new java.awt.Color(0, 0, 0));
        set4_btn.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        set4_btn.setForeground(new java.awt.Color(255, 255, 255));
        set4_btn.setText("Flashcard Set 4");

        set5_btn.setBackground(new java.awt.Color(0, 0, 0));
        set5_btn.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        set5_btn.setForeground(new java.awt.Color(255, 255, 255));
        set5_btn.setText("Flashcard Set 5");

        set6_btn.setBackground(new java.awt.Color(0, 0, 0));
        set6_btn.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        set6_btn.setForeground(new java.awt.Color(255, 255, 255));
        set6_btn.setText("Flashcard Set 6");

        delete_btn.setBackground(new java.awt.Color(0, 0, 0));
        delete_btn.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        delete_btn.setForeground(new java.awt.Color(255, 255, 255));
        delete_btn.setText("Delete All Selected");

        main_menu_btn.setBackground(new java.awt.Color(0, 0, 0));
        main_menu_btn.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        main_menu_btn.setForeground(new java.awt.Color(255, 255, 255));
        main_menu_btn.setText("Main Menu");
        main_menu_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_menu_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(set4_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(set1_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(set5_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(set2_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(set6_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(set3_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(delete_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(main_menu_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(set1_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(set3_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(set2_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(set4_btn)
                    .addComponent(set5_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(set6_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main_menu_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void main_menu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_menu_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_main_menu_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FlashcardDelete().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete_btn;
    private javax.swing.JButton main_menu_btn;
    private javax.swing.JRadioButton set1_btn;
    private javax.swing.JRadioButton set2_btn;
    private javax.swing.JRadioButton set3_btn;
    private javax.swing.JRadioButton set4_btn;
    private javax.swing.JRadioButton set5_btn;
    private javax.swing.JRadioButton set6_btn;
    // End of variables declaration//GEN-END:variables
}
