/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guisource;

import java.io.FileNotFoundException;
import java.util.ArrayList;

/**
 *
 * @author afoud
 */
public class FlashcardFrame extends javax.swing.JFrame {
    
    private ArrayList<String> view_question;
    private ArrayList<String> view_answer;
    private int flashcard_index = 0;
    private int flashcard_index_max;
    private int q_a_switch = 0;
    private ArrayList<String> set_question = new ArrayList<String>();
    private ArrayList<String> set_answer = new ArrayList<String>();
    private String flashcard_set_save;    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FlashcardFrame.class.getName());

    /**
     * Creates new form FlashcardFrame
     */
    public FlashcardFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        home_btn = new javax.swing.JButton();
        view_flashcard_btn = new javax.swing.JButton();
        edit_flashcard_btn = new javax.swing.JButton();
        main_menu_btn = new javax.swing.JButton();
        jpanel_flashcard = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        display_text_btn = new javax.swing.JButton();
        previous_btn = new javax.swing.JButton();
        next_btn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        create_flashcard_btn = new javax.swing.JButton();
        delete_flashcard_btn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        flashcard_question_text = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        flashcard_answer_text = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        add_another_btn = new javax.swing.JButton();
        select_save_box = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        del_set_1 = new javax.swing.JCheckBox();
        del_set_2 = new javax.swing.JCheckBox();
        del_set_3 = new javax.swing.JCheckBox();
        del_set_4 = new javax.swing.JCheckBox();
        del_set_5 = new javax.swing.JCheckBox();
        del_set_6 = new javax.swing.JCheckBox();
        del_flashcard_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        select_view_box = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        home_btn.setText("Home");
        home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btnActionPerformed(evt);
            }
        });

        view_flashcard_btn.setText("View Flashcards");
        view_flashcard_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_flashcard_btnActionPerformed(evt);
            }
        });

        edit_flashcard_btn.setText("Edit Flashcards");
        edit_flashcard_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_flashcard_btnActionPerformed(evt);
            }
        });

        main_menu_btn.setText("Main Menu");
        main_menu_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_menu_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(home_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134)
                .addComponent(view_flashcard_btn)
                .addGap(49, 49, 49)
                .addComponent(edit_flashcard_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(main_menu_btn)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(home_btn)
                    .addComponent(view_flashcard_btn)
                    .addComponent(edit_flashcard_btn)
                    .addComponent(main_menu_btn))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jpanel_flashcard.setEnabled(false);
        jpanel_flashcard.setFocusable(false);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome to the Flashcard Section");

        jTextField2.setBackground(new java.awt.Color(102, 102, 102));
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("Here you can create and view your own flashcards to see how well you are learning !");
        jTextField2.setAlignmentX(0.0F);
        jTextField2.setAlignmentY(0.0F);
        jTextField2.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jpanel_flashcard.addTab("Home", jPanel2);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        display_text_btn.setText("Question");
        display_text_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_text_btnActionPerformed(evt);
            }
        });

        previous_btn.setText("Previous");
        previous_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previous_btnActionPerformed(evt);
            }
        });

        next_btn.setText("Next");
        next_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(previous_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(display_text_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(next_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(display_text_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(previous_btn)
                    .addComponent(next_btn))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jpanel_flashcard.addTab("View Flashcards", jPanel4);

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));

        create_flashcard_btn.setText("Create Flashcard Set");
        create_flashcard_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_flashcard_btnActionPerformed(evt);
            }
        });

        delete_flashcard_btn.setText("Delete Flashcard Set");
        delete_flashcard_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_flashcard_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(create_flashcard_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(delete_flashcard_btn)
                .addGap(151, 151, 151))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create_flashcard_btn)
                    .addComponent(delete_flashcard_btn))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        jpanel_flashcard.addTab("Edit Flashcards", jPanel5);

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));

        flashcard_question_text.setColumns(20);
        flashcard_question_text.setRows(5);
        jScrollPane1.setViewportView(flashcard_question_text);

        flashcard_answer_text.setColumns(20);
        flashcard_answer_text.setRows(5);
        jScrollPane2.setViewportView(flashcard_answer_text);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter your Question");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter your Answer");

        add_another_btn.setText("Add");
        add_another_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_another_btnActionPerformed(evt);
            }
        });

        select_save_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Set 1", "Set 2", "Set 3", "Set 4", "Set 5", "Set 6" }));
        select_save_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_save_boxActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Save as");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(52, 52, 52)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(add_another_btn)
                        .addGap(36, 36, 36))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(select_save_box, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(add_another_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(select_save_box, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        jpanel_flashcard.addTab("Create Flashcards", jPanel6);

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Select what Flashcard to delete");

        del_set_1.setForeground(new java.awt.Color(255, 255, 255));
        del_set_1.setText("Set 1");

        del_set_2.setForeground(new java.awt.Color(255, 255, 255));
        del_set_2.setText("Set 2");

        del_set_3.setForeground(new java.awt.Color(255, 255, 255));
        del_set_3.setText("Set 3");

        del_set_4.setForeground(new java.awt.Color(255, 255, 255));
        del_set_4.setText("Set 4");

        del_set_5.setForeground(new java.awt.Color(255, 255, 255));
        del_set_5.setText("Set 5");

        del_set_6.setForeground(new java.awt.Color(255, 255, 255));
        del_set_6.setText("Set 6");

        del_flashcard_btn.setText("Delete all Selected");
        del_flashcard_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_flashcard_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(del_set_4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(del_set_5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(del_set_6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(del_set_1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(del_set_2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(del_set_3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(308, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(del_flashcard_btn)
                .addGap(134, 134, 134))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(33, 33, 33)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(del_set_1)
                    .addComponent(del_set_2)
                    .addComponent(del_set_3))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(del_set_4)
                    .addComponent(del_set_5)
                    .addComponent(del_set_6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(del_flashcard_btn)
                .addGap(63, 63, 63))
        );

        jpanel_flashcard.addTab("Delete Flashcards", jPanel7);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Choose what flashcard set you would like to view");

        select_view_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Set 1", "Set 2", "Set 3", "Set 4", "Set 5", "Set 6" }));
        select_view_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_view_boxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(select_view_box, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(295, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(68, 68, 68)
                .addComponent(select_view_box, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 132, Short.MAX_VALUE))
        );

        jpanel_flashcard.addTab("Select Flashcards", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanel_flashcard)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpanel_flashcard))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
// Move From Pannel to Pannel and Frame to Frame
    private void home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_btnActionPerformed
        jpanel_flashcard.setSelectedIndex(0);
    }//GEN-LAST:event_home_btnActionPerformed

    private void view_flashcard_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_flashcard_btnActionPerformed
        jpanel_flashcard.setSelectedIndex(5);
    }//GEN-LAST:event_view_flashcard_btnActionPerformed

    private void edit_flashcard_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_flashcard_btnActionPerformed
        jpanel_flashcard.setSelectedIndex(2);
    }//GEN-LAST:event_edit_flashcard_btnActionPerformed

    private void main_menu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_menu_btnActionPerformed
        HomePage home_page = new HomePage();
        home_page.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_main_menu_btnActionPerformed

// When a set it selected to be viewed
    private void select_view_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_view_boxActionPerformed
        var flashcard_set_view = (String) select_view_box.getSelectedItem();

        jpanel_flashcard.setSelectedIndex(1);
        try {
            flashcardView(flashcard_set_view);
        } catch (FileNotFoundException ex) {
            System.getLogger(FlashcardFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
    }//GEN-LAST:event_select_view_boxActionPerformed

// Method for Displaying Question or Answer in View A Flashcard Function
    private void display_text_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display_text_btnActionPerformed
        // TODO add your handling code here:
        
        if (q_a_switch == 0) {
            display_text_btn.setText(this.view_answer.get(this.flashcard_index));
            q_a_switch = 1;
        }
        else {
            display_text_btn.setText(this.view_question.get(this.flashcard_index));
            q_a_switch = 0;
        }
    }//GEN-LAST:event_display_text_btnActionPerformed

// Displaying the next Indexed Flashcard in a Set, Error Handaling for if Index does not exsit
    private void next_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_btnActionPerformed
        // TODO add your handling code here:
        if(flashcard_index < flashcard_index_max -1) {
            this.flashcard_index = flashcard_index + 1;
            display_text_btn.setText(this.view_answer.get(this.flashcard_index));
            display_text_btn.setText(this.view_question.get(this.flashcard_index));
        }
    }//GEN-LAST:event_next_btnActionPerformed

// Displaying the previous Indexed Flashcard in a Set, Error Handaling for if Index does not exsit
    private void previous_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previous_btnActionPerformed
        // TODO add your handling code here:
        if(flashcard_index != 0) {
            this.flashcard_index = flashcard_index - 1;
            display_text_btn.setText(this.view_answer.get(this.flashcard_index));
            display_text_btn.setText(this.view_question.get(this.flashcard_index));
        }
    }//GEN-LAST:event_previous_btnActionPerformed

// When Set is selected pass the sellected set to the Method for saving the new set to the JSON file
    private void select_save_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_save_boxActionPerformed
        jpanel_flashcard.setSelectedIndex(0);
        this.flashcard_set_save = (String) select_save_box.getSelectedItem();
        try {
            flashcard_set();
        } catch (FileNotFoundException ex) {
            System.getLogger(FlashcardFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_select_save_boxActionPerformed

// When the button is pressed Saves the Text in the Text Area to the ArrayLists and Make the Text Area empty
    private void add_another_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_another_btnActionPerformed
   
        this.set_question.add(flashcard_question_text.getText());
        this.set_answer.add(flashcard_answer_text.getText());
        flashcard_question_text.setText(null);
        flashcard_answer_text.setText(null);       
    }//GEN-LAST:event_add_another_btnActionPerformed

    private void create_flashcard_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_flashcard_btnActionPerformed
        jpanel_flashcard.setSelectedIndex(3);
    }//GEN-LAST:event_create_flashcard_btnActionPerformed

// When the button it pressed it checks which boxes are check and then passes it on to the Delete Function
    private void del_flashcard_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_flashcard_btnActionPerformed
        ArrayList<String> delete_set = new ArrayList<String>();
        if (del_set_1.isSelected()) {
            delete_set.add("Set 1");
        }
        if (del_set_2.isSelected()) {
            delete_set.add("Set 2");
        }
        if (del_set_3.isSelected()) {
            delete_set.add("Set 3");
        }
        if (del_set_4.isSelected()) {
            delete_set.add("Set 4");
        }
        if (del_set_5.isSelected()) {
            delete_set.add("Set 5");
        }
        if (del_set_6.isSelected()) {
            delete_set.add("Set 6");
        }
        
        try {
            delete_these_set(delete_set);
        } catch (FileNotFoundException ex) {
            System.getLogger(FlashcardFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        jpanel_flashcard.setSelectedIndex(0);       
        
    }//GEN-LAST:event_del_flashcard_btnActionPerformed

    private void delete_flashcard_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_flashcard_btnActionPerformed
        jpanel_flashcard.setSelectedIndex(4);
    }//GEN-LAST:event_delete_flashcard_btnActionPerformed

    public void delete_these_set(ArrayList<String> delete_set) throws FileNotFoundException {
        flashcardlogic.DeleteFlashcard fcdfc = new flashcardlogic.DeleteFlashcard(delete_set);
    }
// Method for instantiation the ViewFlashcard Class, Adds data on the size of the ArrayList, Displays the first flashcard with index 0
    public void flashcardView(String flashcard_set_view) throws FileNotFoundException {
        
        flashcardlogic.ViewFlashcard fcvfc = new flashcardlogic.ViewFlashcard(flashcard_set_view);
        // Removes perviously loaded flashcards
        if(this.view_question != null) {
            this.view_question.clear();
            this.view_answer.clear();
        }
        
        this.view_question = new ArrayList<String>(fcvfc.get_flashcard_question());
        this.view_answer = new ArrayList<String>(fcvfc.get_flashcard_answer());
        
        this.flashcard_index_max = view_question.size();
        
        display_text_btn.setText(view_question.get(flashcard_index)); 
    }
    
    public void flashcard_set() throws FileNotFoundException {
        flashcardlogic.CreateFlashcard fccf = new flashcardlogic.CreateFlashcard(set_question, set_answer, flashcard_set_save);
        
        set_question.clear();
        set_answer.clear();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_another_btn;
    private javax.swing.JButton create_flashcard_btn;
    private javax.swing.JButton del_flashcard_btn;
    private javax.swing.JCheckBox del_set_1;
    private javax.swing.JCheckBox del_set_2;
    private javax.swing.JCheckBox del_set_3;
    private javax.swing.JCheckBox del_set_4;
    private javax.swing.JCheckBox del_set_5;
    private javax.swing.JCheckBox del_set_6;
    private javax.swing.JButton delete_flashcard_btn;
    private javax.swing.JButton display_text_btn;
    private javax.swing.JButton edit_flashcard_btn;
    private javax.swing.JTextArea flashcard_answer_text;
    private javax.swing.JTextArea flashcard_question_text;
    private javax.swing.JButton home_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTabbedPane jpanel_flashcard;
    private javax.swing.JButton main_menu_btn;
    private javax.swing.JButton next_btn;
    private javax.swing.JButton previous_btn;
    private javax.swing.JComboBox<String> select_save_box;
    private javax.swing.JComboBox<String> select_view_box;
    private javax.swing.JButton view_flashcard_btn;
    // End of variables declaration//GEN-END:variables
}