/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guisource;

import SideSubject.sideSubjectsMath;

/**
 *
 * @author shoai
 */
public class SideSubject3 extends javax.swing.JFrame {

    /**
     * Creates new form SideSubject1
     */
    public SideSubject3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mathLBL = new javax.swing.JLabel();
        Mathematics1LBL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Mathematics2TF = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Mathematics3TF = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        Mathematics1TF = new javax.swing.JTextArea();
        Mathematics2LBL = new javax.swing.JLabel();
        Mathematics3LBL = new javax.swing.JLabel();
        backBTN = new javax.swing.JButton();
        Mathematics1BTN = new javax.swing.JButton();
        Mathematics2BTN = new javax.swing.JButton();
        Mathematics3BTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mathLBL.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        mathLBL.setText("Mathematics");

        Mathematics1LBL.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        Mathematics1LBL.setText("Chapter 1");

        Mathematics2TF.setColumns(20);
        Mathematics2TF.setRows(5);
        jScrollPane1.setViewportView(Mathematics2TF);

        Mathematics3TF.setColumns(20);
        Mathematics3TF.setRows(5);
        jScrollPane2.setViewportView(Mathematics3TF);

        Mathematics1TF.setColumns(20);
        Mathematics1TF.setRows(5);
        jScrollPane3.setViewportView(Mathematics1TF);

        Mathematics2LBL.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        Mathematics2LBL.setText("Chapter 2");

        Mathematics3LBL.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        Mathematics3LBL.setText("Chapter 3");

        backBTN.setBackground(new java.awt.Color(255, 0, 51));
        backBTN.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        backBTN.setText("BACK");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        Mathematics1BTN.setBackground(new java.awt.Color(102, 153, 255));
        Mathematics1BTN.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        Mathematics1BTN.setText("Display 1");
        Mathematics1BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mathematics1BTNActionPerformed(evt);
            }
        });

        Mathematics2BTN.setBackground(new java.awt.Color(102, 153, 255));
        Mathematics2BTN.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        Mathematics2BTN.setText("Display 2");
        Mathematics2BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mathematics2BTNActionPerformed(evt);
            }
        });

        Mathematics3BTN.setBackground(new java.awt.Color(102, 153, 255));
        Mathematics3BTN.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        Mathematics3BTN.setText("Display 3");
        Mathematics3BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mathematics3BTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Mathematics1LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Mathematics1BTN)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(mathLBL)
                            .addGap(240, 240, 240))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Mathematics2LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Mathematics2BTN))
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Mathematics3LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Mathematics3BTN))
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(backBTN)
                            .addGap(18, 18, 18)))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(118, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mathLBL)
                .addGap(18, 18, 18)
                .addComponent(Mathematics1LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(Mathematics1BTN)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Mathematics2LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Mathematics2BTN)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Mathematics3LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Mathematics3BTN)))
                .addGap(26, 26, 26)
                .addComponent(backBTN)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(92, 92, 92)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(382, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Mathematics1BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mathematics1BTNActionPerformed
        // TODO add your handling code here:
        String content = sideSubjectsMath.getChapterContent(1);
    Mathematics1TF.setText(content);
    }//GEN-LAST:event_Mathematics1BTNActionPerformed

    private void Mathematics2BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mathematics2BTNActionPerformed
         String content = sideSubjectsMath.getChapterContent(2);
    Mathematics2TF.setText(content);
    }//GEN-LAST:event_Mathematics2BTNActionPerformed

    private void Mathematics3BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mathematics3BTNActionPerformed
     String content = sideSubjectsMath.getChapterContent(3);
    Mathematics3TF.setText(content);
    }//GEN-LAST:event_Mathematics3BTNActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        setVisible(false);//remove the current screen
        SideSubject ss = new SideSubject();//Link Sidesubjerct to the home page
        ss.setVisible(true);//set its visibility to true
    }//GEN-LAST:event_backBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SideSubject3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SideSubject3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SideSubject3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SideSubject3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SideSubject3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Mathematics1BTN;
    private javax.swing.JLabel Mathematics1LBL;
    private javax.swing.JTextArea Mathematics1TF;
    private javax.swing.JButton Mathematics2BTN;
    private javax.swing.JLabel Mathematics2LBL;
    private javax.swing.JTextArea Mathematics2TF;
    private javax.swing.JButton Mathematics3BTN;
    private javax.swing.JLabel Mathematics3LBL;
    private javax.swing.JTextArea Mathematics3TF;
    private javax.swing.JButton backBTN;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel mathLBL;
    // End of variables declaration//GEN-END:variables
}
