/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guisource;

/**
 *
 * @author Mohammad Shoaib
 */
import guisource.HomePage;
import java.awt.Color;//adding for color changing based on selected item in combo box for quiz, green = right, red - wrong
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;//adding for popups within the gui//cant commit

public class SideSubject extends javax.swing.JFrame {//creating the jframe for the warm educaitonal enviorment



    /**
     * Creates new form RecourceHubGUI
     */
    public SideSubject() {//start jframe constructor
        initComponents();//initialise components
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomePagePanel = new javax.swing.JPanel();
        ReportGeneratorLogoLabel = new javax.swing.JLabel();
        ReportGeneratorLabel = new javax.swing.JLabel();
        RecourceHubLogoLabel = new javax.swing.JLabel();
        RecourceHubLabel = new javax.swing.JLabel();
        ContactUsLogoLabel = new javax.swing.JLabel();
        ContactUsLabel = new javax.swing.JLabel();
        Parent = new javax.swing.JPanel();
        ResourceHubPNL = new javax.swing.JPanel();
        ResourceHubNavPNL = new javax.swing.JPanel();
        ManageRecourceLabel = new javax.swing.JLabel();
        TutorialLabel = new javax.swing.JLabel();
        sideSubjectsLabel = new javax.swing.JLabel();
        ManageResourcesLabel = new javax.swing.JLabel();
        SecondParent = new javax.swing.JPanel();
        TutorialsPNL = new javax.swing.JPanel();
        TutorialLabel2 = new javax.swing.JLabel();
        TutorialLabel3 = new javax.swing.JLabel();
        TutorialLabel5 = new javax.swing.JLabel();
        TutorialLabel4 = new javax.swing.JLabel();
        Tutorial1Label = new javax.swing.JLabel();
        TutorialNameLabel = new javax.swing.JLabel();
        TutorialNameLabel2 = new javax.swing.JLabel();
        TutorialNameLabel3 = new javax.swing.JLabel();
        TutorialNameLabel4 = new javax.swing.JLabel();
        TutorialNameLabel5 = new javax.swing.JLabel();
        exitBTn1 = new javax.swing.JButton();
        ManageResourcesPNL = new javax.swing.JPanel();
        subject3LBL = new javax.swing.JLabel();
        exitBTn8 = new javax.swing.JButton();
        subject1LBL = new javax.swing.JLabel();
        subject2LBL = new javax.swing.JLabel();
        CSicon = new javax.swing.JLabel();
        Chemistryicon = new javax.swing.JLabel();
        mathicon = new javax.swing.JLabel();
        introLBL = new javax.swing.JLabel();
        intro2LBL = new javax.swing.JLabel();
        ReportGeneratorPNL = new javax.swing.JPanel();
        subjectNameLabel = new javax.swing.JLabel();
        chaperLabel = new javax.swing.JLabel();
        NotesLabel = new javax.swing.JLabel();
        ReportGeneratorFirstNameField = new javax.swing.JTextField();
        AVGGradeField = new javax.swing.JTextField();
        ReportGeneratorContentLabel = new javax.swing.JLabel();
        SaveBTN = new javax.swing.JButton();
        ViewBTN = new javax.swing.JButton();
        ReportGeneratorTitleLabel = new javax.swing.JLabel();
        exitBTn6 = new javax.swing.JButton();
        TBLScrollPane = new javax.swing.JScrollPane();
        notesTBL = new javax.swing.JTable();
        NotesTA = new javax.swing.JTextField();
        ContactUsPNL = new javax.swing.JPanel();
        ContactUsTitleLabel = new javax.swing.JLabel();
        ContactUsFirstNameField = new javax.swing.JTextField();
        ContactUsFirstNameLabel = new javax.swing.JLabel();
        ContactUsFeedbackLabel = new javax.swing.JLabel();
        FeedbackTextAreaScrollPane = new javax.swing.JScrollPane();
        FeedbackTextArea = new javax.swing.JTextArea();
        ContactUsTermsAndConditionsLabel = new javax.swing.JLabel();
        ContactUsTermsAndConditionsCheckBox = new javax.swing.JCheckBox();
        ContactUsReviewDateLabel = new javax.swing.JLabel();
        ContactUsReviewDateFormattedField = new javax.swing.JFormattedTextField();
        ContactUsSurnameLabel = new javax.swing.JLabel();
        ContactUsSurnameField = new javax.swing.JTextField();
        ContactUsEmailLabel = new javax.swing.JLabel();
        ContactUsEmailField = new javax.swing.JTextField();
        SendFeedbackBTN = new javax.swing.JButton();
        exitBTn5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 204, 255));

        HomePagePanel.setBackground(new java.awt.Color(153, 153, 153));
        HomePagePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        HomePagePanel.setLayout(null);

        ReportGeneratorLogoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReportGeneratorLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/document.png"))); // NOI18N
        ReportGeneratorLogoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ReportGeneratorLogoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportGeneratorLogoLabelMouseClicked(evt);
            }
        });
        HomePagePanel.add(ReportGeneratorLogoLabel);
        ReportGeneratorLogoLabel.setBounds(30, 30, 70, 70);

        ReportGeneratorLabel.setFont(new java.awt.Font("Bauhaus 93", 1, 12)); // NOI18N
        ReportGeneratorLabel.setForeground(new java.awt.Color(255, 255, 255));
        ReportGeneratorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReportGeneratorLabel.setText("Notes");
        HomePagePanel.add(ReportGeneratorLabel);
        ReportGeneratorLabel.setBounds(10, 100, 100, 24);

        RecourceHubLogoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RecourceHubLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/book.png"))); // NOI18N
        RecourceHubLogoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RecourceHubLogoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RecourceHubLogoLabelMouseClicked(evt);
            }
        });
        HomePagePanel.add(RecourceHubLogoLabel);
        RecourceHubLogoLabel.setBounds(20, 210, 80, 70);

        RecourceHubLabel.setFont(new java.awt.Font("Bauhaus 93", 1, 12)); // NOI18N
        RecourceHubLabel.setForeground(new java.awt.Color(255, 255, 255));
        RecourceHubLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RecourceHubLabel.setText("Recource hub");
        HomePagePanel.add(RecourceHubLabel);
        RecourceHubLabel.setBounds(10, 280, 100, 18);

        ContactUsLogoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ContactUsLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/communicate.png"))); // NOI18N
        ContactUsLogoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ContactUsLogoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContactUsLogoLabelMouseClicked(evt);
            }
        });
        HomePagePanel.add(ContactUsLogoLabel);
        ContactUsLogoLabel.setBounds(20, 370, 80, 70);

        ContactUsLabel.setFont(new java.awt.Font("Bauhaus 93", 1, 12)); // NOI18N
        ContactUsLabel.setForeground(new java.awt.Color(255, 255, 255));
        ContactUsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ContactUsLabel.setText("Contact us");
        HomePagePanel.add(ContactUsLabel);
        ContactUsLabel.setBounds(20, 440, 70, 18);

        Parent.setBackground(new java.awt.Color(255, 255, 255));
        Parent.setLayout(new java.awt.CardLayout());

        ResourceHubPNL.setBackground(new java.awt.Color(51, 204, 255));
        ResourceHubPNL.setLayout(null);

        ResourceHubNavPNL.setBackground(new java.awt.Color(102, 102, 102));
        ResourceHubNavPNL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        ResourceHubNavPNL.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ManageRecourceLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/coordinator.png"))); // NOI18N
        ManageRecourceLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ManageRecourceLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageRecourceLabelMouseClicked(evt);
            }
        });

        TutorialLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/educational-video.png"))); // NOI18N
        TutorialLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TutorialLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TutorialLabelMouseClicked(evt);
            }
        });

        sideSubjectsLabel.setFont(new java.awt.Font("Bauhaus 93", 1, 12)); // NOI18N
        sideSubjectsLabel.setForeground(new java.awt.Color(255, 255, 255));
        sideSubjectsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideSubjectsLabel.setText("Tutorials");

        ManageResourcesLabel.setFont(new java.awt.Font("Bauhaus 93", 1, 12)); // NOI18N
        ManageResourcesLabel.setForeground(new java.awt.Color(255, 255, 255));
        ManageResourcesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ManageResourcesLabel.setText("Manage recources");

        javax.swing.GroupLayout ResourceHubNavPNLLayout = new javax.swing.GroupLayout(ResourceHubNavPNL);
        ResourceHubNavPNL.setLayout(ResourceHubNavPNLLayout);
        ResourceHubNavPNLLayout.setHorizontalGroup(
            ResourceHubNavPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResourceHubNavPNLLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(ResourceHubNavPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sideSubjectsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TutorialLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 392, Short.MAX_VALUE)
                .addGroup(ResourceHubNavPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResourceHubNavPNLLayout.createSequentialGroup()
                        .addComponent(ManageRecourceLabel)
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResourceHubNavPNLLayout.createSequentialGroup()
                        .addComponent(ManageResourcesLabel)
                        .addGap(104, 104, 104))))
        );
        ResourceHubNavPNLLayout.setVerticalGroup(
            ResourceHubNavPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResourceHubNavPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ResourceHubNavPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TutorialLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManageRecourceLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ResourceHubNavPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sideSubjectsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManageResourcesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        ResourceHubPNL.add(ResourceHubNavPNL);
        ResourceHubNavPNL.setBounds(0, 0, 690, 130);

        SecondParent.setLayout(new java.awt.CardLayout());

        TutorialsPNL.setBackground(new java.awt.Color(153, 153, 153));

        TutorialLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TutorialLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/video-lesson.png"))); // NOI18N
        TutorialLabel2.setToolTipText("Please press on the labels to open tutorials!");
        TutorialLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TutorialLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TutorialLabel2MouseClicked(evt);
            }
        });

        TutorialLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TutorialLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/video-lesson.png"))); // NOI18N
        TutorialLabel3.setToolTipText("Please press on the labels to open tutorials!");
        TutorialLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TutorialLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TutorialLabel3MouseClicked(evt);
            }
        });

        TutorialLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TutorialLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/video-lesson.png"))); // NOI18N
        TutorialLabel5.setToolTipText("Please press on the labels to open tutorials!");
        TutorialLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TutorialLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TutorialLabel5MouseClicked(evt);
            }
        });

        TutorialLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TutorialLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/video-lesson.png"))); // NOI18N
        TutorialLabel4.setToolTipText("Please press on the labels to open tutorials!");
        TutorialLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TutorialLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TutorialLabel4MouseClicked(evt);
            }
        });

        Tutorial1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tutorial1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/video-lesson.png"))); // NOI18N
        Tutorial1Label.setToolTipText("Please press on the labels to open tutorials!");
        Tutorial1Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tutorial1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tutorial1LabelMouseClicked(evt);
            }
        });

        TutorialNameLabel.setFont(new java.awt.Font("Bauhaus 93", 1, 12)); // NOI18N
        TutorialNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TutorialNameLabel.setText("Tutorial 1");

        TutorialNameLabel2.setFont(new java.awt.Font("Bauhaus 93", 1, 12)); // NOI18N
        TutorialNameLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TutorialNameLabel2.setText("Tutorial 2");

        TutorialNameLabel3.setFont(new java.awt.Font("Bauhaus 93", 1, 12)); // NOI18N
        TutorialNameLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TutorialNameLabel3.setText("Tutorial 3");

        TutorialNameLabel4.setFont(new java.awt.Font("Bauhaus 93", 1, 12)); // NOI18N
        TutorialNameLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TutorialNameLabel4.setText("Tutorial 4");

        TutorialNameLabel5.setFont(new java.awt.Font("Bauhaus 93", 1, 12)); // NOI18N
        TutorialNameLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TutorialNameLabel5.setText("Tutorial 5");

        exitBTn1.setBackground(new java.awt.Color(255, 51, 51));
        exitBTn1.setText("EXIT");
        exitBTn1.setToolTipText("Please hit the exit button to return to the homescreen");
        exitBTn1.setMaximumSize(new java.awt.Dimension(72, 22));
        exitBTn1.setMinimumSize(new java.awt.Dimension(72, 22));
        exitBTn1.setPreferredSize(new java.awt.Dimension(72, 22));
        exitBTn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TutorialsPNLLayout = new javax.swing.GroupLayout(TutorialsPNL);
        TutorialsPNL.setLayout(TutorialsPNLLayout);
        TutorialsPNLLayout.setHorizontalGroup(
            TutorialsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TutorialsPNLLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(TutorialsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TutorialsPNLLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(TutorialNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)
                        .addComponent(TutorialNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TutorialNameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))
                    .addGroup(TutorialsPNLLayout.createSequentialGroup()
                        .addGroup(TutorialsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TutorialsPNLLayout.createSequentialGroup()
                                .addGroup(TutorialsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Tutorial1Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TutorialLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(97, 97, 97)
                                .addGroup(TutorialsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TutorialLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TutorialLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(86, 86, 86)
                                .addComponent(TutorialLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(TutorialsPNLLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(TutorialsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(exitBTn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(TutorialsPNLLayout.createSequentialGroup()
                                        .addComponent(TutorialNameLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(143, 143, 143)
                                        .addComponent(TutorialNameLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(100, Short.MAX_VALUE))))
        );
        TutorialsPNLLayout.setVerticalGroup(
            TutorialsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TutorialsPNLLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(TutorialsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TutorialLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TutorialLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tutorial1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TutorialsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TutorialsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TutorialNameLabel)
                        .addComponent(TutorialNameLabel2))
                    .addComponent(TutorialNameLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(TutorialsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TutorialLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TutorialLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TutorialsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TutorialNameLabel4)
                    .addComponent(TutorialNameLabel5))
                .addGap(18, 18, 18)
                .addComponent(exitBTn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        SecondParent.add(TutorialsPNL, "card2");

        ManageResourcesPNL.setBackground(new java.awt.Color(153, 153, 153));
        ManageResourcesPNL.setLayout(null);

        subject3LBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        subject3LBL.setForeground(new java.awt.Color(255, 255, 255));
        subject3LBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subject3LBL.setText("Mathematics");
        ManageResourcesPNL.add(subject3LBL);
        subject3LBL.setBounds(290, 250, 120, 25);

        exitBTn8.setBackground(new java.awt.Color(255, 51, 51));
        exitBTn8.setText("EXIT");
        exitBTn8.setToolTipText("Hit this button to return to the home screen!");
        exitBTn8.setMaximumSize(new java.awt.Dimension(72, 22));
        exitBTn8.setMinimumSize(new java.awt.Dimension(72, 22));
        exitBTn8.setPreferredSize(new java.awt.Dimension(72, 22));
        exitBTn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTn8ActionPerformed(evt);
            }
        });
        ManageResourcesPNL.add(exitBTn8);
        exitBTn8.setBounds(600, 350, 70, 20);

        subject1LBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        subject1LBL.setForeground(new java.awt.Color(255, 255, 255));
        subject1LBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subject1LBL.setText("Computer Science");
        ManageResourcesPNL.add(subject1LBL);
        subject1LBL.setBounds(10, 240, 170, 25);

        subject2LBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        subject2LBL.setForeground(new java.awt.Color(255, 255, 255));
        subject2LBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subject2LBL.setText(" Chemistry");
        ManageResourcesPNL.add(subject2LBL);
        subject2LBL.setBounds(550, 240, 120, 25);

        CSicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-computer-science-68.png"))); // NOI18N
        ManageResourcesPNL.add(CSicon);
        CSicon.setBounds(50, 170, 90, 70);

        Chemistryicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-chemistry-book-64.png"))); // NOI18N
        ManageResourcesPNL.add(Chemistryicon);
        Chemistryicon.setBounds(580, 160, 70, 80);

        mathicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-maths-book-100.png"))); // NOI18N
        ManageResourcesPNL.add(mathicon);
        mathicon.setBounds(290, 150, 110, 100);

        introLBL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        introLBL.setForeground(new java.awt.Color(255, 255, 255));
        introLBL.setText("Side Subjects ");
        ManageResourcesPNL.add(introLBL);
        introLBL.setBounds(200, 10, 250, 50);

        intro2LBL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        intro2LBL.setForeground(new java.awt.Color(255, 255, 255));
        intro2LBL.setText("Choose Your Side Subject By Clicking on the Icon");
        ManageResourcesPNL.add(intro2LBL);
        intro2LBL.setBounds(130, 60, 400, 30);

        SecondParent.add(ManageResourcesPNL, "card4");

        ResourceHubPNL.add(SecondParent);
        SecondParent.setBounds(0, 130, 690, 380);

        Parent.add(ResourceHubPNL, "card3");

        ReportGeneratorPNL.setBackground(new java.awt.Color(51, 204, 255));
        ReportGeneratorPNL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ReportGeneratorPNL.setLayout(null);

        subjectNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subjectNameLabel.setText("Subject Name");
        ReportGeneratorPNL.add(subjectNameLabel);
        subjectNameLabel.setBounds(30, 90, 100, 16);

        chaperLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chaperLabel.setText("Chaper No#");
        ReportGeneratorPNL.add(chaperLabel);
        chaperLabel.setBounds(390, 90, 76, 16);

        NotesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NotesLabel.setText("Notes");
        ReportGeneratorPNL.add(NotesLabel);
        NotesLabel.setBounds(40, 150, 62, 16);

        ReportGeneratorFirstNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ReportGeneratorFirstNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ReportGeneratorFirstNameFieldKeyPressed(evt);
            }
        });
        ReportGeneratorPNL.add(ReportGeneratorFirstNameField);
        ReportGeneratorFirstNameField.setBounds(130, 90, 120, 22);

        AVGGradeField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AVGGradeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportGeneratorAVGGradeFieldActionPerformed(evt);
            }
        });
        AVGGradeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AVGGradeFieldKeyPressed(evt);
            }
        });
        ReportGeneratorPNL.add(AVGGradeField);
        AVGGradeField.setBounds(490, 90, 120, 22);

        ReportGeneratorContentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReportGeneratorContentLabel.setText("Notes");
        ReportGeneratorPNL.add(ReportGeneratorContentLabel);
        ReportGeneratorContentLabel.setBounds(310, 260, 62, 16);

        SaveBTN.setText("Save");
        SaveBTN.setToolTipText("Please fill in the fields listed above to save your report, when you hit the save button, feedback will be generated to notify you how your doing in your course based on your average grade!");
        SaveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBTNActionPerformed(evt);
            }
        });
        ReportGeneratorPNL.add(SaveBTN);
        SaveBTN.setBounds(100, 470, 130, 23);

        ViewBTN.setText("view");
        ViewBTN.setToolTipText("Please press this view button to populate the table");
        ViewBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBTNActionPerformed(evt);
            }
        });
        ReportGeneratorPNL.add(ViewBTN);
        ViewBTN.setBounds(310, 470, 107, 23);

        ReportGeneratorTitleLabel.setFont(new java.awt.Font("Bauhaus 93", 1, 36)); // NOI18N
        ReportGeneratorTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        ReportGeneratorTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReportGeneratorTitleLabel.setText("Notes ");
        ReportGeneratorPNL.add(ReportGeneratorTitleLabel);
        ReportGeneratorTitleLabel.setBounds(181, 31, 295, 36);

        exitBTn6.setBackground(new java.awt.Color(255, 51, 51));
        exitBTn6.setText("EXIT");
        exitBTn6.setToolTipText("Press this button to return to home");
        exitBTn6.setMaximumSize(new java.awt.Dimension(72, 22));
        exitBTn6.setMinimumSize(new java.awt.Dimension(72, 22));
        exitBTn6.setPreferredSize(new java.awt.Dimension(72, 22));
        exitBTn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTn6ActionPerformed(evt);
            }
        });
        ReportGeneratorPNL.add(exitBTn6);
        exitBTn6.setBounds(500, 470, 104, 22);

        notesTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "SubjectName", "Chapter", "Notes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBLScrollPane.setViewportView(notesTBL);

        ReportGeneratorPNL.add(TBLScrollPane);
        TBLScrollPane.setBounds(40, 290, 620, 123);
        ReportGeneratorPNL.add(NotesTA);
        NotesTA.setBounds(110, 150, 520, 100);

        Parent.add(ReportGeneratorPNL, "card4");

        ContactUsPNL.setBackground(new java.awt.Color(153, 153, 153));

        ContactUsTitleLabel.setFont(new java.awt.Font("Bauhaus 93", 1, 36)); // NOI18N
        ContactUsTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        ContactUsTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ContactUsTitleLabel.setText("Contact Us");

        ContactUsFirstNameField.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ContactUsFirstNameField.setToolTipText("Please enter your first name into this field.\n");
        ContactUsFirstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactUsFirstNameFieldActionPerformed(evt);
            }
        });
        ContactUsFirstNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ContactUsFirstNameFieldKeyPressed(evt);
            }
        });

        ContactUsFirstNameLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ContactUsFirstNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        ContactUsFirstNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ContactUsFirstNameLabel.setText("FirstName");

        ContactUsFeedbackLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ContactUsFeedbackLabel.setForeground(new java.awt.Color(255, 255, 255));
        ContactUsFeedbackLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ContactUsFeedbackLabel.setText("Feedback");

        FeedbackTextArea.setColumns(20);
        FeedbackTextArea.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        FeedbackTextArea.setRows(5);
        FeedbackTextArea.setToolTipText("Please enter your review into this text area on your experience with said component.");
        FeedbackTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FeedbackTextAreaKeyPressed(evt);
            }
        });
        FeedbackTextAreaScrollPane.setViewportView(FeedbackTextArea);

        ContactUsTermsAndConditionsLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ContactUsTermsAndConditionsLabel.setForeground(new java.awt.Color(255, 255, 255));
        ContactUsTermsAndConditionsLabel.setText("Terms and conditions");

        ContactUsTermsAndConditionsCheckBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ContactUsTermsAndConditionsCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        ContactUsTermsAndConditionsCheckBox.setText("I Accept");
        ContactUsTermsAndConditionsCheckBox.setToolTipText("Please accept the terms and conditions in order to submit a review.");
        ContactUsTermsAndConditionsCheckBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ContactUsReviewDateLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ContactUsReviewDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        ContactUsReviewDateLabel.setText("ReviewDate");

        ContactUsReviewDateFormattedField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        ContactUsReviewDateFormattedField.setToolTipText("Please enter the date that the review is being submitted.");
        ContactUsReviewDateFormattedField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactUsReviewDateFormattedFieldActionPerformed(evt);
            }
        });
        ContactUsReviewDateFormattedField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ContactUsReviewDateFormattedFieldKeyPressed(evt);
            }
        });

        ContactUsSurnameLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ContactUsSurnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        ContactUsSurnameLabel.setText("Surname");

        ContactUsSurnameField.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ContactUsSurnameField.setToolTipText("Please enter your surname into this field.");
        ContactUsSurnameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ContactUsSurnameFieldKeyPressed(evt);
            }
        });

        ContactUsEmailLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ContactUsEmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        ContactUsEmailLabel.setText("Email");

        ContactUsEmailField.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        ContactUsEmailField.setToolTipText("Please enter your email into this field, for e.g. 'michael.moore@example.com'");
        ContactUsEmailField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ContactUsEmailFieldKeyPressed(evt);
            }
        });

        SendFeedbackBTN.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        SendFeedbackBTN.setText("Send");
        SendFeedbackBTN.setToolTipText("After you've filled out all of the fields above and want to submit your review, please press this 'send' button.\n");
        SendFeedbackBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SendFeedbackBTN.setMaximumSize(new java.awt.Dimension(72, 22));
        SendFeedbackBTN.setMinimumSize(new java.awt.Dimension(72, 22));
        SendFeedbackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendFeedbackBTNActionPerformed(evt);
            }
        });

        exitBTn5.setBackground(new java.awt.Color(255, 51, 51));
        exitBTn5.setText("EXIT");
        exitBTn5.setToolTipText("Please press this button to return home!");
        exitBTn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBTn5.setMaximumSize(new java.awt.Dimension(72, 22));
        exitBTn5.setMinimumSize(new java.awt.Dimension(72, 22));
        exitBTn5.setPreferredSize(new java.awt.Dimension(72, 22));
        exitBTn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTn5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContactUsPNLLayout = new javax.swing.GroupLayout(ContactUsPNL);
        ContactUsPNL.setLayout(ContactUsPNLLayout);
        ContactUsPNLLayout.setHorizontalGroup(
            ContactUsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContactUsPNLLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(ContactUsFeedbackLabel)
                .addGap(18, 18, 18)
                .addGroup(ContactUsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContactUsPNLLayout.createSequentialGroup()
                        .addComponent(ContactUsTermsAndConditionsLabel)
                        .addGap(18, 18, 18)
                        .addComponent(ContactUsTermsAndConditionsCheckBox)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ContactUsPNLLayout.createSequentialGroup()
                        .addGroup(ContactUsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ContactUsEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContactUsFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ContactUsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContactUsPNLLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ContactUsSurnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ContactUsSurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ContactUsPNLLayout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(ContactUsReviewDateLabel)
                                .addGap(18, 18, 18)
                                .addComponent(ContactUsReviewDateFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38))
                    .addGroup(ContactUsPNLLayout.createSequentialGroup()
                        .addComponent(FeedbackTextAreaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(ContactUsPNLLayout.createSequentialGroup()
                .addGroup(ContactUsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContactUsPNLLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(ContactUsEmailLabel))
                    .addGroup(ContactUsPNLLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ContactUsFirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContactUsPNLLayout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(SendFeedbackBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(exitBTn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContactUsPNLLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(ContactUsTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ContactUsPNLLayout.setVerticalGroup(
            ContactUsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContactUsPNLLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(ContactUsTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ContactUsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContactUsFirstNameLabel)
                    .addComponent(ContactUsFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContactUsSurnameLabel)
                    .addComponent(ContactUsSurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(ContactUsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContactUsReviewDateLabel)
                    .addComponent(ContactUsReviewDateFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContactUsEmailLabel)
                    .addComponent(ContactUsEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96)
                .addGroup(ContactUsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContactUsFeedbackLabel)
                    .addComponent(FeedbackTextAreaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContactUsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContactUsTermsAndConditionsLabel)
                    .addComponent(ContactUsTermsAndConditionsCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(ContactUsPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SendFeedbackBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitBTn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        Parent.add(ContactUsPNL, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HomePagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomePagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContactUsFirstNameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContactUsFirstNameFieldKeyPressed
       
    }//GEN-LAST:event_ContactUsFirstNameFieldKeyPressed

    private void FeedbackTextAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FeedbackTextAreaKeyPressed

    }//GEN-LAST:event_FeedbackTextAreaKeyPressed

    private void ContactUsReviewDateFormattedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactUsReviewDateFormattedFieldActionPerformed

    }//GEN-LAST:event_ContactUsReviewDateFormattedFieldActionPerformed

    private void ContactUsReviewDateFormattedFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContactUsReviewDateFormattedFieldKeyPressed

    }//GEN-LAST:event_ContactUsReviewDateFormattedFieldKeyPressed

    private void ContactUsSurnameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContactUsSurnameFieldKeyPressed
        String Text = ContactUsSurnameField.getText();//get text as a string from the Field element within the GUI
        int InpLength = 30;//setting the length limit of the field

        int code = evt.getKeyCode();//getting code for key pressed

        if ((code >= KeyEvent.VK_A && code <= KeyEvent.VK_Z)//if condition to ensure the end user is only able to enter the expected input and cant break the program
                || (code >= KeyEvent.VK_0 && code <= KeyEvent.VK_9)//if condition to ensure the end user is only able to enter the expected input and cant break the program
                || code == KeyEvent.VK_BACK_SPACE) {//allow the end user to hit backspace

            if (Text.length() >= InpLength && code != KeyEvent.VK_BACK_SPACE) {//allow backspace if the limit is reached
                JOptionPane.showMessageDialog(null, "Most allowed is 30 inputs for surname!");//notify the end user if it was succesful or not using j option pane popup
                evt.consume();//stops the key press from happenign
            }//end if
        } else {//start else if condition
            JOptionPane.showMessageDialog(null, "Wrong input. Please use valid name inputs.");//notify the end user if it was succesful or not using j option pane popup
            evt.consume();//stops the key press from happenign
        }//end if
    }//GEN-LAST:event_ContactUsSurnameFieldKeyPressed

    private void ContactUsEmailFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContactUsEmailFieldKeyPressed

    }//GEN-LAST:event_ContactUsEmailFieldKeyPressed

    private void SendFeedbackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendFeedbackBTNActionPerformed
    
    }//GEN-LAST:event_SendFeedbackBTNActionPerformed

    private void ContactUsFirstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactUsFirstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactUsFirstNameFieldActionPerformed

    private void ReportGeneratorAVGGradeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportGeneratorAVGGradeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReportGeneratorAVGGradeFieldActionPerformed

    private void ReportGeneratorLogoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportGeneratorLogoLabelMouseClicked
        Parent.removeAll();//using the card layout to switch  beetween panels, so i remove all at the beginning to avoid overlapping
        Parent.add(ReportGeneratorPNL);//call upon the desired panel that the end user has clicked
        Parent.repaint();//repainting thr parent panel to get the cuurent desired view in the CardLayout
        Parent.revalidate();//revalidaiting the parent panel to make sure the layout is properly updated

    }//GEN-LAST:event_ReportGeneratorLogoLabelMouseClicked

    private void RecourceHubLogoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecourceHubLogoLabelMouseClicked
        Parent.removeAll();//using the card layout to switch  beetween panels, so i remove all at the beginning to avoid overlapping
        Parent.add(ResourceHubPNL);//call upon the desired panel that the end user has clicked
        Parent.repaint();//repainting thr parent panel to get the cuurent desired view in the CardLayout
        Parent.revalidate();//revalidaiting the parent panel to make sure the layout is properly updated
    }//GEN-LAST:event_RecourceHubLogoLabelMouseClicked

    private void ContactUsLogoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactUsLogoLabelMouseClicked
        Parent.removeAll();//using the card layout to switch  beetween panels, so i remove all at the beginning to avoid overlapping
        Parent.add(ContactUsPNL);//call upon the desired panel that the end user has clicked
        Parent.repaint();//repainting thr parent panel to get the cuurent desired view in the CardLayout
        Parent.revalidate();//revalidaiting the parent panel to make sure the layout is properly updated
    }//GEN-LAST:event_ContactUsLogoLabelMouseClicked

    private void TutorialLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TutorialLabelMouseClicked
        SecondParent.removeAll();//using the card layout to switch  beetween panels, so i remove all at the beginning to avoid overlapping
        SecondParent.add(TutorialsPNL);//call upon the desired panel that the end user has clicked
        SecondParent.repaint();//repainting thr parent panel to get the cuurent desired view in the CardLayout
        SecondParent.revalidate();//revalidaiting the parent panel to make sure the layout is properly updated
    }//GEN-LAST:event_TutorialLabelMouseClicked

    private void exitBTn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTn1ActionPerformed
        setVisible(false);//remove the current screen
        HomePage homePage = new HomePage();//create the of the homepage
        homePage.setVisible(true);//set its visibility to true
    }//GEN-LAST:event_exitBTn1ActionPerformed

    private void exitBTn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTn5ActionPerformed
        setVisible(false);//remove the current screen
        HomePage homePage = new HomePage();//create the of the homepage
        homePage.setVisible(true);//set its visibility to true
    }//GEN-LAST:event_exitBTn5ActionPerformed

    private void exitBTn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTn6ActionPerformed
        setVisible(false);//remove the current screen
        HomePage homePage = new HomePage();//create the of the homepage
        homePage.setVisible(true);//set its visibility to true
    }//GEN-LAST:event_exitBTn6ActionPerformed

    private void Tutorial1LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tutorial1LabelMouseClicked
     
    }//GEN-LAST:event_Tutorial1LabelMouseClicked

    private void TutorialLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TutorialLabel2MouseClicked
   
    }//GEN-LAST:event_TutorialLabel2MouseClicked

    private void TutorialLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TutorialLabel3MouseClicked

    }//GEN-LAST:event_TutorialLabel3MouseClicked

    private void TutorialLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TutorialLabel4MouseClicked

    }//GEN-LAST:event_TutorialLabel4MouseClicked

    private void TutorialLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TutorialLabel5MouseClicked
  
    }//GEN-LAST:event_TutorialLabel5MouseClicked

    private void ViewBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBTNActionPerformed
     
    }//GEN-LAST:event_ViewBTNActionPerformed

    private void SaveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBTNActionPerformed
 
    }//GEN-LAST:event_SaveBTNActionPerformed

    private void exitBTn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTn8ActionPerformed

         HomePage homePage = new HomePage();//create the of the homepage
        homePage.setVisible(true);//set its visibility to true
    }//GEN-LAST:event_exitBTn8ActionPerformed

    private void ReportGeneratorFirstNameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ReportGeneratorFirstNameFieldKeyPressed
        String Text = ReportGeneratorFirstNameField.getText();//get text as a string from the Field element within the GUI
        int InpLength = 30;//setting the length limit of the field

        int code = evt.getKeyCode();//getting code for key pressed

        if ((code >= KeyEvent.VK_A && code <= KeyEvent.VK_Z)//if condition to ensure the end user is only able to enter the expected input and cant break the program
                || code == KeyEvent.VK_BACK_SPACE) {//allow the end user to hit backspace

            if (Text.length() >= InpLength && code != KeyEvent.VK_BACK_SPACE) {//allow backspace if the limit is reached
                JOptionPane.showMessageDialog(null, "Most allowed is 30 inputs for name!");//notify the end user if it was succesful or not using j option pane popup
                evt.consume();//stops the key press from happenign
            }//end if
        } else {//start else if condition
            JOptionPane.showMessageDialog(null, "Wrong input. Please use valid email inputs.");//notify the end user if it was succesful or not using j option pane popup
            evt.consume();//stops the key press from happenign
        }//end if
    }//GEN-LAST:event_ReportGeneratorFirstNameFieldKeyPressed

    private void AVGGradeFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AVGGradeFieldKeyPressed
        String Text = AVGGradeField.getText();//get text as a string from the Field element within the GUI
        int InpLength = 5;//setting the length limit of the field

        int code = evt.getKeyCode();//getting code for key pressed

        if ((code >= KeyEvent.VK_0 && code <= KeyEvent.VK_9)//if condition to ensure the end user is only able to enter the expected input and cant break the program
                || code == KeyEvent.VK_BACK_SPACE) {//allow the end user to hit backspace

            if (Text.length() >= InpLength && code != KeyEvent.VK_BACK_SPACE) {//allow backspace if the limit is reached
                JOptionPane.showMessageDialog(null, "Most allowed is 5 inputs for grade!");//notify the end user if it was succesful or not using j option pane popup
                evt.consume();//stops the key press from happenign
            }//end if
        } else {//start else if condition
            JOptionPane.showMessageDialog(null, "Wrong input. Please use valid email inputs.");//notify the end user if it was succesful or not using j option pane popup
            evt.consume();//stops the key press from happenign
        }//end if
    }//GEN-LAST:event_AVGGradeFieldKeyPressed

    private void ManageRecourceLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageRecourceLabelMouseClicked
        SecondParent.removeAll();//using the card layout to switch  beetween panels, so i remove all at the beginning to avoid overlapping
        SecondParent.add(ManageResourcesPNL);//call upon the desired panel that the end user has clicked
        SecondParent.repaint();//repainting thr parent panel to get the cuurent desired view in the CardLayout
        SecondParent.revalidate();//revalidaiting the parent panel to make sure the layout is properly updated
    }//GEN-LAST:event_ManageRecourceLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SideSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SideSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SideSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SideSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new SideSubject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AVGGradeField;
    private javax.swing.JLabel CSicon;
    private javax.swing.JLabel Chemistryicon;
    public static javax.swing.JTextField ContactUsEmailField;
    private javax.swing.JLabel ContactUsEmailLabel;
    private javax.swing.JLabel ContactUsFeedbackLabel;
    public static javax.swing.JTextField ContactUsFirstNameField;
    private javax.swing.JLabel ContactUsFirstNameLabel;
    private javax.swing.JLabel ContactUsLabel;
    private javax.swing.JLabel ContactUsLogoLabel;
    private javax.swing.JPanel ContactUsPNL;
    private javax.swing.JFormattedTextField ContactUsReviewDateFormattedField;
    private javax.swing.JLabel ContactUsReviewDateLabel;
    public static javax.swing.JTextField ContactUsSurnameField;
    private javax.swing.JLabel ContactUsSurnameLabel;
    private javax.swing.JCheckBox ContactUsTermsAndConditionsCheckBox;
    private javax.swing.JLabel ContactUsTermsAndConditionsLabel;
    private javax.swing.JLabel ContactUsTitleLabel;
    public static javax.swing.JTextArea FeedbackTextArea;
    private javax.swing.JScrollPane FeedbackTextAreaScrollPane;
    private javax.swing.JPanel HomePagePanel;
    private javax.swing.JLabel ManageRecourceLabel;
    private javax.swing.JLabel ManageResourcesLabel;
    private javax.swing.JPanel ManageResourcesPNL;
    private javax.swing.JLabel NotesLabel;
    private javax.swing.JTextField NotesTA;
    private javax.swing.JPanel Parent;
    private javax.swing.JLabel RecourceHubLabel;
    private javax.swing.JLabel RecourceHubLogoLabel;
    private javax.swing.JLabel ReportGeneratorContentLabel;
    private javax.swing.JTextField ReportGeneratorFirstNameField;
    private javax.swing.JLabel ReportGeneratorLabel;
    private javax.swing.JLabel ReportGeneratorLogoLabel;
    private javax.swing.JPanel ReportGeneratorPNL;
    private javax.swing.JLabel ReportGeneratorTitleLabel;
    private javax.swing.JPanel ResourceHubNavPNL;
    private javax.swing.JPanel ResourceHubPNL;
    private javax.swing.JButton SaveBTN;
    private javax.swing.JPanel SecondParent;
    public static javax.swing.JButton SendFeedbackBTN;
    private javax.swing.JScrollPane TBLScrollPane;
    private javax.swing.JLabel Tutorial1Label;
    private javax.swing.JLabel TutorialLabel;
    private javax.swing.JLabel TutorialLabel2;
    private javax.swing.JLabel TutorialLabel3;
    private javax.swing.JLabel TutorialLabel4;
    private javax.swing.JLabel TutorialLabel5;
    private javax.swing.JLabel TutorialNameLabel;
    private javax.swing.JLabel TutorialNameLabel2;
    private javax.swing.JLabel TutorialNameLabel3;
    private javax.swing.JLabel TutorialNameLabel4;
    private javax.swing.JLabel TutorialNameLabel5;
    private javax.swing.JPanel TutorialsPNL;
    private javax.swing.JButton ViewBTN;
    private javax.swing.JLabel chaperLabel;
    private javax.swing.JButton exitBTn1;
    private javax.swing.JButton exitBTn5;
    private javax.swing.JButton exitBTn6;
    private javax.swing.JButton exitBTn8;
    private javax.swing.JLabel intro2LBL;
    private javax.swing.JLabel introLBL;
    private javax.swing.JLabel mathicon;
    private javax.swing.JTable notesTBL;
    private javax.swing.JLabel sideSubjectsLabel;
    private javax.swing.JLabel subject1LBL;
    private javax.swing.JLabel subject2LBL;
    private javax.swing.JLabel subject3LBL;
    private javax.swing.JLabel subjectNameLabel;
    // End of variables declaration//GEN-END:variables
}
