/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eduapp;

/**
 *
 * @author ikram
 */
public class SubjectsGUI extends javax.swing.JFrame {

    /**
     * Creates new form QuizGUI
     */
    public SubjectsGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        QuizMainPNL = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DisplayTA = new javax.swing.JTextArea();
        CoreRB = new javax.swing.JRadioButton();
        SideRB = new javax.swing.JRadioButton();
        CustomeRB = new javax.swing.JRadioButton();
        QuizSubjectsPNL = new javax.swing.JPanel();
        SidePNL = new javax.swing.JPanel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        CustomPNL = new javax.swing.JPanel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        CorePNL = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        MenuBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        AnswerBTN = new javax.swing.JButton();
        TitleLBL = new javax.swing.JLabel();
        TimerLBL = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TimerTA = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        QuizMainPNL.setBackground(new java.awt.Color(0, 102, 102));
        QuizMainPNL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.cyan, java.awt.Color.white, java.awt.Color.black, java.awt.Color.lightGray));

        DisplayTA.setBackground(new java.awt.Color(0, 0, 0));
        DisplayTA.setColumns(20);
        DisplayTA.setForeground(new java.awt.Color(255, 255, 255));
        DisplayTA.setRows(5);
        jScrollPane1.setViewportView(DisplayTA);

        CoreRB.setForeground(new java.awt.Color(255, 255, 255));
        CoreRB.setText("Core Subjects");
        CoreRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoreRBActionPerformed(evt);
            }
        });

        SideRB.setForeground(new java.awt.Color(255, 255, 255));
        SideRB.setText("Side Subjects");
        SideRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SideRBActionPerformed(evt);
            }
        });

        CustomeRB.setForeground(new java.awt.Color(255, 255, 255));
        CustomeRB.setText("Custom Subjects");
        CustomeRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomeRBActionPerformed(evt);
            }
        });

        QuizSubjectsPNL.setLayout(new java.awt.CardLayout());

        SidePNL.setBackground(new java.awt.Color(0, 0, 0));
        SidePNL.setForeground(new java.awt.Color(255, 255, 255));

        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Subject 1");

        jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("Subject 2");

        jRadioButton6.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setText("Subject 3");

        javax.swing.GroupLayout SidePNLLayout = new javax.swing.GroupLayout(SidePNL);
        SidePNL.setLayout(SidePNLLayout);
        SidePNLLayout.setHorizontalGroup(
            SidePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePNLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SidePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        SidePNLLayout.setVerticalGroup(
            SidePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePNLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton6)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        QuizSubjectsPNL.add(SidePNL, "card3");

        CustomPNL.setBackground(new java.awt.Color(0, 0, 0));

        jRadioButton7.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setText("Subject 3");

        jRadioButton8.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton8.setText("Subject 2");

        jRadioButton9.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton9.setText("Subject 1");

        javax.swing.GroupLayout CustomPNLLayout = new javax.swing.GroupLayout(CustomPNL);
        CustomPNL.setLayout(CustomPNLLayout);
        CustomPNLLayout.setHorizontalGroup(
            CustomPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustomPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton7))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        CustomPNLLayout.setVerticalGroup(
            CustomPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton7)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        QuizSubjectsPNL.add(CustomPNL, "card4");

        CorePNL.setBackground(new java.awt.Color(0, 0, 0));
        CorePNL.setForeground(new java.awt.Color(255, 255, 255));

        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Subject 1");

        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Subject 2");

        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Subject 3");

        javax.swing.GroupLayout CorePNLLayout = new javax.swing.GroupLayout(CorePNL);
        CorePNL.setLayout(CorePNLLayout);
        CorePNLLayout.setHorizontalGroup(
            CorePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CorePNLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CorePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        CorePNLLayout.setVerticalGroup(
            CorePNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CorePNLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        QuizSubjectsPNL.add(CorePNL, "card2");

        MenuBTN.setBackground(new java.awt.Color(0, 0, 0));
        MenuBTN.setForeground(new java.awt.Color(255, 255, 255));
        MenuBTN.setText("Main Menu");
        MenuBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBTNActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select Answer:");

        jRadioButton10.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton10.setText("A");

        jRadioButton11.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton11.setText("B");

        jRadioButton12.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton12.setText("C");

        AnswerBTN.setBackground(new java.awt.Color(0, 0, 0));
        AnswerBTN.setForeground(new java.awt.Color(255, 255, 255));
        AnswerBTN.setText("Answer");

        TitleLBL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TitleLBL.setForeground(new java.awt.Color(255, 255, 255));
        TitleLBL.setText("Quiz");

        TimerLBL.setForeground(new java.awt.Color(255, 255, 255));
        TimerLBL.setText("Timer:");

        TimerTA.setBackground(new java.awt.Color(0, 0, 0));
        TimerTA.setColumns(20);
        TimerTA.setForeground(new java.awt.Color(255, 255, 255));
        TimerTA.setRows(5);
        jScrollPane2.setViewportView(TimerTA);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quiz logo.png"))); // NOI18N

        javax.swing.GroupLayout QuizMainPNLLayout = new javax.swing.GroupLayout(QuizMainPNL);
        QuizMainPNL.setLayout(QuizMainPNLLayout);
        QuizMainPNLLayout.setHorizontalGroup(
            QuizMainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizMainPNLLayout.createSequentialGroup()
                .addGroup(QuizMainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuizMainPNLLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(MenuBTN))
                    .addGroup(QuizMainPNLLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(QuizMainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(QuizMainPNLLayout.createSequentialGroup()
                                .addGroup(QuizMainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(QuizMainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(QuizMainPNLLayout.createSequentialGroup()
                                            .addGroup(QuizMainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(CoreRB)
                                                .addComponent(SideRB)
                                                .addComponent(CustomeRB))
                                            .addGap(18, 18, 18)
                                            .addComponent(QuizSubjectsPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel1)
                                        .addComponent(jRadioButton10)
                                        .addComponent(jRadioButton11)
                                        .addComponent(jRadioButton12)
                                        .addComponent(AnswerBTN)))
                                .addGap(18, 18, 18)
                                .addGroup(QuizMainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TimerLBL)))
                            .addGroup(QuizMainPNLLayout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addComponent(TitleLBL)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        QuizMainPNLLayout.setVerticalGroup(
            QuizMainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuizMainPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QuizMainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TitleLBL)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(QuizMainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuizMainPNLLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(CoreRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SideRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CustomeRB))
                    .addComponent(QuizSubjectsPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(QuizMainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(QuizMainPNLLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(QuizMainPNLLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(TimerLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AnswerBTN)
                .addGap(18, 18, 18)
                .addComponent(MenuBTN)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(QuizMainPNL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(QuizMainPNL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustomeRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomeRBActionPerformed
        // TODO add your handling code here:
        CustomPNL.setVisible(true);
        CorePNL.setVisible(false);
        SidePNL.setVisible(false);
    }//GEN-LAST:event_CustomeRBActionPerformed

    private void CoreRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoreRBActionPerformed
        // TODO add your handling code here:
        CorePNL.setVisible(true);
        CustomPNL.setVisible(false);
        SidePNL.setVisible(false);
    }//GEN-LAST:event_CoreRBActionPerformed

    private void SideRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SideRBActionPerformed
        // TODO add your handling code here:
        SidePNL.setVisible(true);
        CustomPNL.setVisible(false);
        CorePNL.setVisible(false);
    }//GEN-LAST:event_SideRBActionPerformed

    private void MenuBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBTNActionPerformed
        // TODO add your handling code here:
        setVisible(false);//remove the current screen
        HomePage homePage = new HomePage();//create the of the homepage
        homePage.setVisible(true);//set its visibility to true
    }//GEN-LAST:event_MenuBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubjectsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnswerBTN;
    private javax.swing.JPanel CorePNL;
    private javax.swing.JRadioButton CoreRB;
    private javax.swing.JPanel CustomPNL;
    private javax.swing.JRadioButton CustomeRB;
    private javax.swing.JTextArea DisplayTA;
    private javax.swing.JButton MenuBTN;
    private javax.swing.JPanel QuizMainPNL;
    private javax.swing.JPanel QuizSubjectsPNL;
    private javax.swing.JPanel SidePNL;
    private javax.swing.JRadioButton SideRB;
    private javax.swing.JLabel TimerLBL;
    private javax.swing.JTextArea TimerTA;
    private javax.swing.JLabel TitleLBL;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
